// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVIVlcydqVIzKPIS44m3etqTFq5hvMxGY',
    appId: '1:863209070202:web:b5da0b507fd731f7a725c3',
    messagingSenderId: '863209070202',
    projectId: 'calendar-mot',
    authDomain: 'calendar-mot.firebaseapp.com',
    storageBucket: 'calendar-mot.firebasestorage.app',
    measurementId: 'G-FQ4NVZ2PCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPL6JLH9Q8n0aVKpasG9_BTJ212UZfK04',
    appId: '1:863209070202:android:300e524d6adc1454a725c3',
    messagingSenderId: '863209070202',
    projectId: 'calendar-mot',
    storageBucket: 'calendar-mot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Xhg_ub_u4aB8l5baD_PUAV8FiTqu-4Y',
    appId: '1:863209070202:ios:e88cf6ce5eba0549a725c3',
    messagingSenderId: '863209070202',
    projectId: 'calendar-mot',
    storageBucket: 'calendar-mot.firebasestorage.app',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Xhg_ub_u4aB8l5baD_PUAV8FiTqu-4Y',
    appId: '1:863209070202:ios:e88cf6ce5eba0549a725c3',
    messagingSenderId: '863209070202',
    projectId: 'calendar-mot',
    storageBucket: 'calendar-mot.firebasestorage.app',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVIVlcydqVIzKPIS44m3etqTFq5hvMxGY',
    appId: '1:863209070202:web:608a03680223f60aa725c3',
    messagingSenderId: '863209070202',
    projectId: 'calendar-mot',
    authDomain: 'calendar-mot.firebaseapp.com',
    storageBucket: 'calendar-mot.firebasestorage.app',
    measurementId: 'G-1TTP4JX3FM',
  );

}